site_name: Notes
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  locale: en
  static_templates:
    - sitemap.html
  include_sidebar: false
  color_mode: dark
  user_color_mode_toggle: true